version = 1.0 #The current configuration version, DO NOT CHANGE THIS

[jda]
token = ""                         #your bots token
activity = "Beep Boop, Boop Beep?" #your activity as its displayed in the discord client
activity_type = "PLAYING"          #the activity type to use
gateway_intents = [
    "GUILD_BANS",
    "GUILD_EMOJIS",
    "GUILD_VOICE_STATES",
    "GUILD_MESSAGES",
    "GUILD_MESSAGE_REACTIONS"
]                                  #the gateway intents to use, you can specify any of the intents listed here https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/requests/GatewayIntent.html
enabled_cache_flags = [
    "VOICE_STATE",
    "EMOTE",
    "MEMBER_OVERRIDES"
]                                  #cache flags to use, keeping this empty will make the api automatically figure out what cache flags to use. You can specify any of the cache flags listed here https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/utils/cache/CacheFlag.html
disabled_cache_flags = [
    "ACTIVITY",
    "CLIENT_STATUS"
]                                  #cache flags to not use, it can be useful to disable certain cache flags to save memory and bandwidth
chunking_filter = "NONE"           #the chunking filter to use, this should be kept at NONE but you can set it to any of https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/utils/ChunkingFilter.html
member_cache_policy = "DEFAULT"    #it's recommended to keep this as DEFAULT, but if need be you can set it to any of https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/utils/MemberCachePolicy.html
auto_reconnect = true              #whether to automatically attempt reconnecting to Discord after an error
bulk_delete_splitting = false      #this is recommended to be kept disabled and instead use MessageBulkDeleteEvent
shard_total = -1                   #set to -1 to use discords recommended shard count instead, this is advised.
shard_min = -1                     #the minimum shard ID
shard_max = -1                     #the maximum shard ID
use-jda-nas = false                #only enable this function if you're using lavaplayer for audio streaming https://github.com/sedmelluq/jda-nas
jda-nas-buffer-size = 400          #how big the buffer size will be for jda-nas, this is recommended to keep it at default

[client]
language = "en_GB"                 #the file name not including the .properties file type
prefix = "!"                       #this is the default prefix used for commands, change it as you wish. Modules may override this setting at runtime by using the Module#setPrefixGenerator function
command_timeout_after = 5_000      #how long (in milliseconds) commands may be able to run for, this is for the watchdog thread so if something goes wrong with a command it doesn't slowly consume all the worker threads

[dbl]
auto-post = false #whether to auto post bot stats to top.gg's api, https://top.gg
token = ""

#A list of User-ID's representing Administrators, you can retrieve your user ID by enabling
#developer mode and then right clicking the user and hit "Copy ID"
#after that then restart the bot and you will be able to use owner only commands.
bot_admins = []

#configure metric logging, this requires that you have a valid and properly setup database.
[metrics]
enabled = false
metrics_table = "metrics"

#Your database credentials, set enabled = false to disable database connections if you don't have one.
#The API uses HikariCP for its database connections. https://github.com/brettwooldridge/HikariCP
[db]
enabled = false                     #whether to use the database for GuildSettings, if enabled this will automatically create a table of its own
database_type = "postgresql"        #choose from mysql, mariadb or postgresql. Default is Postgresql and the reason for this is explained on the repository.
database = "discord"                #the database to use
username = "user"                   #the username for authentication
password = "pass"                   #the password for authentication
host = "localhost"                  #where your database is hosted, be it localhost or an IP address
port = 5432                         #the port your database runs on, this is usually 5432 for postgres and 3306 for MySQL/MariaDB
poolSize = 15                        #the connection pool size, more isn't better and is often more harmful than good. https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing