[jda]
    token = ""                         #your bots token
    activity = "Beep Boop, Boop Beep?" #your activity as its displayed in the discord client
    gateway_intents = [
        "GUILD_BANS",
        "GUILD_EMOJIS",
        "GUILD_VOICE_STATES",
        "GUILD_MESSAGES",
        "GUILD_MESSAGE_REACTIONS"
    ]                                  #the gateway intents to use, you can specify any of the intents listed here https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/requests/GatewayIntent.html
    enabled_cache_flags = [
        "VOICE_STATE",
        "EMOTE",
        "MEMBER_OVERRIDES"
    ]                                  #cache flags to use, keeping this empty will make the api automatically figure out what cache flags to use. You can specify any of the cache flags listed here https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/utils/cache/CacheFlag.html
    disabled_cache_flags = [
        "ACTIVITY",
        "CLIENT_STATUS"
    ]                                  #cache flags to not use, it can be useful to disable certain cache flags to save memory and bandwidth
    chunking_filter = "NONE"           #the chunking filter to use, this should be kept at NONE but you can set it to any of https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/utils/ChunkingFilter.html
    member_cache_policy = "DEFAULT"    #it's recommended to keep this as DEFAULT, but if need be you can set it to any of https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/utils/MemberCachePolicy.html
    auto_reconnect = true              #whether to automatically attempt reconnecting to Discord after an error
    bulk_delete_splitting = false      #this is recommended to be kept disabled and instead use MessageBulkDeleteEvent
    shard_total = -1                   #set to -1 to use discords recommended shard count instead, this is advised.
    shard_min = -1                     #the minimum shard ID
    shard_max = -1                     #the maximum shard ID

[client]
    languageFile = "en_GB"             #the file name not including the .properties file type
    prefix = ">"                       #this is the prefix used for commands, change it as you wish

#A list of User-ID's representing Administrators
bot_admins = []

#Your database credentials, set enabled = false to disable database connections if you don't have one
#This api currently only supports use of PostgreSQL, you can find out how to set it up here
#https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-ubuntu-18-04
[db]
    enabled = false                     #whether to use the database for GuildSettings, if enabled this will automatically create a table of its own
    database = "discord"                #the postgres database to use
    username = "user"                   #the username for authentication
    password = "pass"                   #the password for authentication
    host = "localhost"                  #where your database is hosted, be it localhost or an IP address
    port = 5432                         #the port your postgresql database runs on, this is usually 5432 but can be changed
    poolSize = 5                        #the connection pool size, more isn't better. https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing